pipeline {
  agent any
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Package') {
      steps {
        sh '''
          cd "Session 3"
          rm -rf dist && mkdir dist
          cp index.html styles.css script.js dist/
        '''
      }
    }
    stage('Archive') {
      steps {
        archiveArtifacts artifacts: 'Session 3/dist/**', fingerprint: true
      }
    }
  }
}
